import marimo

__generated_with = "0.20.4"
app = marimo.App(
    width="columns",
    app_title="From tool calls to MCP",
    layout_file="layouts/function_call.slides.json",
    sql_output="native",
)

with app.setup:
    from openai import OpenAI
    import marimo as mo

    client = OpenAI()


    def get_horoscope(sign):
        return f"{sign}: Next Tuesday you will befriend a baby otter."


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    # Step 1: Client only
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    No agents SDKs, just the way my grandma used to do it in 2023.
    """)
    return


@app.cell
def _():
    TOOL_REGISTRY = {get_horoscope.__name__: get_horoscope}
    return (TOOL_REGISTRY,)


@app.cell
def _():
    # why didn't OpenAI find a way to do this in their native client?
    tools = [
        {
            "type": "function",
            "name": "get_horoscope",
            "description": "Get today's horoscope for an astrological sign.",
            "parameters": {
                "type": "object",
                "properties": {
                    "sign": {
                        "type": "string",
                        "description": "An astrological sign like Taurus or Aquarius",
                    },
                },
                "required": ["sign"],
            },
        },
    ]
    return (tools,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Then we can pass this list of tools in the usual `client.responses.create()` call.
    """)
    return


@app.cell
def _(tools):
    input_list = [
        {"role": "user", "content": "What is my horoscope? I am a Taurus."},
    ]

    response = client.responses.create(
        model="gpt-5.2",
        tools=tools,
        input=input_list,
    )
    return (response,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Let's inspect the result.
    """)
    return


@app.cell
def _(response):
    mo.inspect(response)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Notice the `output` field. It's a list of a Pydantic models, and here there's just one and it's a `ResponseFunctionToolCall`:
    """)
    return


@app.cell
def _(response):
    mo.inspect(response.output[0])
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    We can use the `response.output.name` and `response.output.arguments` to invoke the tool in our registry:
    """)
    return


@app.cell
def _(TOOL_REGISTRY, response):
    import json


    def call_tool(item, tool_registry=TOOL_REGISTRY):
        if item.type == "function_call":
            tool_name, kwargs = item.name, json.loads(item.arguments)

            try:
                chosen_tool = TOOL_REGISTRY[tool_name]
            except IndexError as e:
                raise ValueError("This tool does not exist") from e

        return chosen_tool(**kwargs)


    call_tool(response.output[0])
    return call_tool, json


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Now let's hook this into the model logic, so it can automatically call the tools, call
    """)
    return


@app.cell
def _(TOOL_REGISTRY, call_tool, json, tools):
    def ask_horoscope(prompt, client, tool_registry=TOOL_REGISTRY):
        input_list = [{"role": "user", "content": prompt}]

        response = client.responses.create(
            model="gpt-5.2",
            tools=tools,  # the global tools defined in the first cell
            input=input_list,
        )

        # Save function call outputs for subsequent requests
        input_list += response.output

        for item in response.output:
            result = call_tool(item)

            input_list.append(
                {
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps(
                        {"tool_name": item.name, "tool_output": result}
                    ),
                }
            )

        print("Final input:")
        print(input_list)

        response = client.responses.create(
            model="gpt-5",
            instructions="Respond only with a horoscope generated by a tool.",
            tools=tools,
            input=input_list,
        )

        # 5. The model should be able to give a response!
        print("Final output:")
        print(response.model_dump_json(indent=2))
        print("\n" + response.output_text)


    ask_horoscope(
        "I am a taurus",
        client,
    )
    return


@app.cell(column=1, hide_code=True)
def _():
    mo.md(r"""
    # Step 2: Agent Frameworks
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Same horoscope example, but with `pydantic-ai` handling tool-calling loops for us.

    This is actually a pretty useful abstraction, [is it not](https://octomind.dev/blog/why-we-no-longer-use-langchain-for-building-our-ai-agents)?
    """)
    return


@app.cell
def _():
    from pydantic_ai import Agent

    horoscope_agent = Agent(
        "openai:gpt-5.2",
        system_prompt="Respond only with a horoscope generated by a tool.",
    )
    return Agent, horoscope_agent


@app.cell
def _(horoscope_agent):
    @horoscope_agent.tool_plain
    def get_horoscope_tool(sign: str) -> str:
        """Get today's horoscope for an astrological sign."""
        return get_horoscope(sign)

    return


@app.cell
async def _(horoscope_agent):
    result = await horoscope_agent.run("I am a taurus")

    result.output
    return


@app.cell(column=2, hide_code=True)
def _():
    mo.md(r"""
    # Step 3: MCP + Agent
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Same horoscope use case, but now the agent gets tools from MCP servers:
    - local `server.py` via `FastMCP`
    - public DeepWiki MCP (`https://mcp.deepwiki.com/mcp`, no auth)
    """)
    return


@app.cell
def _(Agent):
    import sys

    from pydantic_ai.mcp import MCPServerStdio, MCPServerStreamableHTTP

    local_horoscope_mcp = MCPServerStdio(
        sys.executable,
        args=["server.py"],
        tool_prefix="horoscope",
    )
    public_deepwiki_mcp = MCPServerStreamableHTTP(
        "https://mcp.deepwiki.com/mcp",
        tool_prefix="deepwiki",
    )

    mcp_agent = Agent(
        "openai:gpt-5.2",
        system_prompt="For horoscope requests, use the horoscope MCP tool.",
        toolsets=[local_horoscope_mcp, public_deepwiki_mcp],
    )
    return (mcp_agent,)


@app.cell
def _(mcp_agent):
    mcp_chat = mo.ui.chat(
        mo.ai.llm.pydantic_ai(mcp_agent),
        prompts=[
            "I am a Taurus. What's the horoscope for next week?",
            "How is an agent loop implemented in PydanticAI?.",
            "Show me the available tools before answering.",
        ],
        show_configuration_controls=True,
    )
    mcp_chat
    return


if __name__ == "__main__":
    app.run()
